# Generated by Django 4.2.6 on 2024-03-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id_team', models.OneToOneField(db_column='id_team', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='calendar_basket.teams')),
                ('posicion', models.BigIntegerField(blank=True, null=True)),
                ('jugados', models.BigIntegerField(blank=True, null=True)),
                ('puntos', models.BigIntegerField(blank=True, null=True)),
                ('ganados', models.BigIntegerField(blank=True, null=True)),
                ('perdidos', models.BigIntegerField(blank=True, null=True)),
                ('puntos_favor', models.BigIntegerField(blank=True, null=True)),
                ('puntos_contra', models.BigIntegerField(blank=True, null=True)),
                ('racha', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'clasificacion',
                'managed': True,
            },
        ),
    ]
