# Generated by Django 4.2.6 on 2024-03-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_basket', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStatistics',
            fields=[
                ('id_team', models.BigIntegerField(primary_key=True, serialize=False)),
                ('team', models.TextField(blank=True, null=True)),
                ('posicion', models.BigIntegerField(blank=True, null=True)),
                ('jugados', models.BigIntegerField(blank=True, null=True)),
                ('ganados', models.BigIntegerField(blank=True, null=True)),
                ('perdidos', models.BigIntegerField(blank=True, null=True)),
                ('puntos_favor', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('puntos_contra', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('dif_puntos', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('g_puntos_favor', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('g_puntos_contra', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('g_dif_puntos', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('p_puntos_favor', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('p_puntos_contra', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('p_dif_puntos', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('c_posicion', models.BigIntegerField(blank=True, null=True)),
                ('c_jugados', models.BigIntegerField(blank=True, null=True)),
                ('c_ganados', models.BigIntegerField(blank=True, null=True)),
                ('c_perdidos', models.BigIntegerField(blank=True, null=True)),
                ('c_puntos_favor', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('c_puntos_contra', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('c_dif_puntos', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('c_g_puntos_favor', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('c_g_puntos_contra', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('c_g_dif_puntos', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('c_p_puntos_favor', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('c_p_puntos_contra', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('c_p_dif_puntos', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('f_posicion', models.BigIntegerField(blank=True, null=True)),
                ('f_jugados', models.BigIntegerField(blank=True, null=True)),
                ('f_ganados', models.BigIntegerField(blank=True, null=True)),
                ('f_perdidos', models.BigIntegerField(blank=True, null=True)),
                ('f_puntos_favor', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('f_puntos_contra', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('f_dif_puntos', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('f_g_puntos_favor', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('f_g_puntos_contra', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('f_g_dif_puntos', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('f_p_puntos_favor', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('f_p_puntos_contra', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('f_p_dif_puntos', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'team_statistics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mins', models.BigIntegerField(blank=True, default=0, null=True)),
                ('fgm', models.BigIntegerField(blank=True, default=0, null=True)),
                ('fga', models.BigIntegerField(blank=True, default=0, null=True)),
                ('fgperc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('threepm', models.BigIntegerField(blank=True, default=0, null=True)),
                ('threepa', models.BigIntegerField(blank=True, default=0, null=True)),
                ('threepperc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('ftm', models.BigIntegerField(blank=True, default=0, null=True)),
                ('fta', models.BigIntegerField(blank=True, default=0, null=True)),
                ('ftperc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('reb', models.BigIntegerField(blank=True, default=0, null=True)),
                ('ast', models.BigIntegerField(blank=True, default=0, null=True)),
                ('stl', models.BigIntegerField(blank=True, default=0, null=True)),
                ('blk', models.BigIntegerField(blank=True, default=0, null=True)),
                ('turnover', models.BigIntegerField(blank=True, default=0, null=True)),
                ('pf', models.BigIntegerField(blank=True, default=0, null=True)),
                ('pts', models.BigIntegerField(blank=True, default=0, null=True)),
                ('win', models.BooleanField(blank=True, default=False, null=True)),
                ('id_game', models.ForeignKey(blank=True, db_column='id_game', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calendar_basket.calendar')),
                ('id_player', models.ForeignKey(blank=True, db_column='id_player', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.players')),
                ('id_team', models.ForeignKey(blank=True, db_column='id_team', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calendar_basket.teams')),
            ],
            options={
                'db_table': 'statistics',
                'managed': True,
                'unique_together': {('id_game', 'id_player', 'id_team')},
            },
        ),
        migrations.CreateModel(
            name='ShotStatistics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('x', models.BigIntegerField(blank=True, null=True)),
                ('y', models.BigIntegerField(blank=True, null=True)),
                ('made', models.BooleanField(blank=True, default=False, null=True)),
                ('threep', models.BooleanField(blank=True, default=False, null=True)),
                ('id_game', models.ForeignKey(blank=True, db_column='id_game', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calendar_basket.calendar')),
                ('id_player', models.ForeignKey(blank=True, db_column='id_player', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.players')),
                ('id_statistics', models.ForeignKey(blank=True, db_column='id_statistics', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='statistics_basketball.statistics')),
                ('id_team', models.ForeignKey(blank=True, db_column='id_team', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calendar_basket.teams')),
            ],
            options={
                'db_table': 'shot_statistics',
                'managed': True,
            },
        ),
    ]
